spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bike?serverTimezone=UTC
    username: 'root'
    password: '@S2a0s0h2'
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
